name: Docs
on:
  push:
    branches: [ main ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.4
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: luarocks install --only-deps ldoc-dev-1.rockspec
    - name: Build docs
      run: ldoc .
    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/
        force_orphan: true
        publish_branch: github-pages
